# Permalinks
permalink:           pretty

# Setup
title:               Ian Tracey
tagline:             software+startups+coffee 
url:                 https://ianrtracey.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# About/contact
author:
  name:              Ian Tracey 
  url:               https://twitter.com/ianrtracey
  email:             ianrtracey@gmail.com
  twitter:
    username: ianrtracey

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
excerpt_separator: "<!--more-->"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
